### ISSUE TITLE
两个小意见

### ISSUE THREAD

**Issue by cq-guojia** [PingPlusPlus/pingpp-android#12]
1、SDK在调起微信支付的时候如果能判断一下，没有装微信就返回一个错误就最好了。。。
不然还要自己去判断
2、最好能支持gradle引用方式。。。这样就很方便了

**Comment by samurai00** [comment]
1. 微信没有安装，`pay_result` 会返回 `invalid`；
2. gradle 方式有在考虑中

**Comment by samurai00** [comment]
gradle 已支持
