### ISSUE TITLE
alipay crash （关于权限问题）

### ISSUE THREAD

**Issue by SongCF** [PingPlusPlus/pingpp-android#13]
platform：android **4.4.2**
device：**sony xperia**
sdk version: libpingpp-**2.0.5**

目前仅在该设备发现此奔溃，在选择发起**支付宝支付**时，360安全卫士（**极客版**）提示app**获取应用列表的权限**，选择**禁止**后，只要调用支付宝支付就会崩溃。
目前只发现该环境会有获取应用列表的权限。

---

堆栈：
```
java.lang.NullPointerException
com.alipay.sdk.util.h.a(Unknown Source)
com.alipay.sdk.app.PayTask.pay(Unknown Source)
com.pingplusplus.android.a.run(Unknown Source)
```

**Comment by SongCF** [comment]
我们的其它测试设备暂未发现 请求 **获取应用列表的权限**

**Comment by samurai00** [comment]
我们这边的测试设备也没发现这个问题。
只有支付宝会有这个问题吗？

**Comment by SongCF** [comment]
@samurai00 
是的

**Comment by peacepassion** [comment]
@SongCF @samurai00  我也遇到了这个问题，原因还没有查明。请问，这个问题有进展么？

**Comment by peacepassion** [comment]
@SongCF @samurai00 找到问题了，是因为用的alipaylib中获取用户APP安装列表的时候，没有做try/catch保护，升级到最新的alipaylib就用try/catch保护了一下，问题就解决了。

**Comment by samurai00** [comment]
@peacepassion 多谢提供信息。我们换一下新的支付宝 lib。

**Comment by 471448446** [comment]
具体怎么加请问

**Comment by dong11** [comment]
@471448446  你遇到这个错误了吗？ 是最新版SDK吗？

**Comment by 471448446** [comment]
没 我是在小米手机上面，只要是miui8的都要crash

**Comment by dong11** [comment]
@471448446 有log日志吗？  看一下具体的报错信息

**Comment by 471448446** [comment]
@dong11 就是没有日志，一调用pay()就崩溃了。

**Comment by dong11** [comment]
@471448446 alipay的jar包是什么版本？？

**Comment by 471448446** [comment]
最新的，然后alipaySdk-20160812 也要崩。目前发现只要是miui8以上都要崩，

**Comment by 471448446** [comment]
@dong11 但是运行官方的demo又不会崩

**Comment by dong11** [comment]
Ping++SDK 是什么版本？？

**Comment by 471448446** [comment]
@dong11 我只集成了阿里的支付sdk。

**Comment by 471448446** [comment]
@dong11  所以你的问题不是这个？

**Comment by Morsiesml** [comment]
是的现在只要 miui8 以上   直接就崩溃

**Comment by Morsiesml** [comment]
@471448446  请问一下你的这个问题解决了么

**Comment by dong11** [comment]
你们是接入了Ping++SDK后遇到的问题？还是单独在使用AlipaySDK的时候出现的问题？ @Morsiesml

**Comment by Morsiesml** [comment]
@dong11 单独使用AlipaySDK的时候

**Comment by dong11** [comment]
alipay 的jar包版本是多少？

**Comment by Morsiesml** [comment]
@dong11 从2015的版本到现在的alipaySdk-20161129  都不行

**Comment by dong11** [comment]
@Morsiesml 你试过Ping++的SDK吗   会出现这个问题吗？

**Comment by Morsiesml** [comment]
@dong11 正在编译

**Comment by Morsiesml** [comment]
@dong11   用了你里面的jar好像可以了 是重新打包过了的吗
