### ISSUE TITLE
每个平台的包依赖未描述清楚

### ISSUE THREAD

**Issue by lijy91** [PingPlusPlus/pingpp-android#17]
/lib/libs 目录里包含了支付宝，微信支付，银联三个平台，应该把每个平台依赖哪些文件列出来，避免加入不需要的平台。so库并没有说明是哪个平台的。

**Comment by NoGirlFriendException** [comment]
银联支付依赖：UPPayAssisEx.jar、UPPayPluginExPro.jar、android-support-v4.jar、pingpp/libs 目录下的 .so 文件和 pingpp/assets 目录下的 data.bin 文件 

你确定你认真看文档了么- -兄弟...
