### ISSUE TITLE
支付与微信分享发生冲突

### ISSUE THREAD

**Issue by halfapple** [PingPlusPlus/pingpp-android#19]
android studio ide：
1. app 中可以微信分享成功，即原本sdk中有 libammsdk.jar 
2. 按照最新的方式导入，发现 pingapp 中的 libammsdk 与原有冲突，并且与原有的不一样。
如果保留pingapp的 libammsdk，会导致build 失败，具体是微信sdk中 api.sendReq(req) 这个方法失败。
如果保留微信原有libammsdk.jar，则使用时，报告 NoClassDefFoundError，具体就是：

java.lang.NoClassDefFoundError:
Failed resolution of: Lcom/tencent/mm/sdk/modelpay/PayReq;

开发请指导如何解决？

**Comment by halfapple** [comment]
补充截图：保留微信原有的 libammsdk.jar 出现的问题：
![device-2016-02-01-201229](https://cloud.githubusercontent.com/assets/2860999/12717455/00bcf68c-c923-11e5-9961-324d502d8e97.png)

**Comment by halfapple** [comment]
![920cf8bd-2f19-4871-9b32-f43fba7a9173](https://cloud.githubusercontent.com/assets/2860999/12717665/3645b48c-c924-11e5-9fcd-1b000a48d8d9.png)

NoClassDefFoundError 的截图

**Comment by samurai00** [comment]
你原来的 libammsdk 是什么版本的呢？我们这边用的是比较新的版本。

**Comment by halfapple** [comment]
libammsdk 从微信最新的 demo 中提取

**Comment by halfapple** [comment]
解决：使用分支207版本的 libammsdk，并修改部分微信原有的share 代码即可。
