### ISSUE TITLE
Rejecting re-init on previously-failed class java.lang.Class<com.pingplusplus.android.b>

### ISSUE THREAD

**Issue by beiliubei** [PingPlusPlus/pingpp-android#21]
支付宝支付，跳转后，页面是个透明的页面，点击返回 ，toast 出来cancel，但是没有看到支付的页面

**Comment by samurai00** [comment]
麻烦贴一下完整的报错信息，还有你的 manifest 配置和调用代码。

**Comment by beiliubei** [comment]
![image](https://cloud.githubusercontent.com/assets/1127875/13736046/bfcfffc2-e9eb-11e5-8ea6-b2c9917e394f.png)

![image](https://cloud.githubusercontent.com/assets/1127875/13736053/cb30df1c-e9eb-11e5-988b-83ba9d68fd3a.png)

**Comment by beiliubei** [comment]
执行完之后，一个透明蒙版，应该是 PaymentActivity的页面， 点击返回后，弹出toast 显示 cancel

**Comment by samurai00** [comment]
不手动点击返回的话，一直在空白页面是吗？
你打开 Debug 模式，看看有哪些 log 信息。PingppLog.DEBUG = true;

**Comment by beiliubei** [comment]
![image](https://cloud.githubusercontent.com/assets/1127875/13737331/5048d302-e9f7-11e5-82e0-183b0a78d6e1.png)


api返回的charge信息中没有credential信息 是什么原因？

**Comment by samurai00** [comment]
你这个是在客户端打印出来的吗？服务端应该是自己做了 json 解析吧，不要自己做，服务端直接把 Charge 对象当字符串使用。或者如果是 Java 的，用 chargeObject.toString()
