### ISSUE TITLE
官网开发文档跟下载文档不一样

### ISSUE THREAD

**Issue by WangHow123** [PingPlusPlus/pingpp-android#27]
我该听谁的，而且导入能不能说详细点，怎么导入怎么错，现在最新文档只用导入bdwallet_pay_sdk，pingpp，但是文档还有pingpp_one，到底该怎么的?

**Comment by samurai00** [comment]
pingpp_one 是壹收款，pingpp 是没有界面的 SDK，所以看你需求。如果不需要壹收款，实际使用时，就不需要导入 pingpp_one。
