### ISSUE TITLE
有没有cordova的插件？

### ISSUE THREAD

**Issue by cjy37** [PingPlusPlus/pingpp-android#28]

**Comment by samurai00** [comment]
https://github.com/TongChia/cordova-plugin-pingpp
https://github.com/litaoyu/cordova-plugin-pingpp
你可以看下这两个

**Comment by cjy37** [comment]
TongChia/cordova-plugin-pingpp ios报错无法安装。。。
litaoyu/cordova-plugin-pingpp 维护是否及时这个不太清楚啊，要是哪天不维护了不是要命吗，
这可是支付啊

所以，希望官方维护一份，或者官方介入以上插件共同维护 @samurai00

**Comment by samurai00** [comment]
https://coding.net/u/pingplusplus/p/pingpp-cordova/git
