### ISSUE TITLE
.wxapi.WXPayEntryActivity

### ISSUE THREAD

**Issue by longtaoge** [PingPlusPlus/pingpp-android#29]
<activity-alias
            android:name=".wxapi.WXPayEntryActivity"
            android:exported="true"
android:targetActivity="com.pingplusplus.android.PaymentActivity" />
这个Activity 究竟是怎么回事，如果没有这个类无法编译，但是建这么一个页面是做什么的？

**Comment by samurai00** [comment]
给微信回调用的。微信回调只认这个 activity

**Comment by longtaoge** [comment]
有一件事一定要说明白，这个类不用自己新建  
build.gradle  中的 applicationId 和 
AndroidManifest 中的   package  不同时
    android:name=".wxapi.WXPayEntryActivity"
要写成     
 android:name="应用id(applicationId ).wxapi.WXPayEntryActivity"

**Comment by samurai00** [comment]
对的。因为这个是 alias。
