### ISSUE TITLE
.so包有问题

### ISSUE THREAD

**Issue by wublack** [PingPlusPlus/pingpp-android#33]
jniLibs/mips下的so包拒绝访问

**Comment by dong11** [comment]
有具体的log吗？

**Comment by wublack** [comment]
gradle编译运行的时候
![image](https://cloud.githubusercontent.com/assets/10573644/18261693/a6561afa-742d-11e6-9d50-495dc171d545.png)

**Comment by dong11** [comment]
Ping++SDK 版本号是多少？

**Comment by wublack** [comment]
最新的v2.1.6

**Comment by wublack** [comment]
我昨天下载的

**Comment by wublack** [comment]
现在又好了，我就重新复制一遍，覆盖全部，现在运行又不报错了，上午我都替换了好几次，都有问题，请解释一下什么鬼

**Comment by dong11** [comment]
替换的时候 重新build一下   有时候studio  会缓存着
