### ISSUE TITLE
RuntimeException on latest version 2.1.6

### ISSUE THREAD

**Issue by username4gh** [PingPlusPlus/pingpp-android#34]
While using this version, it throws an exception described below:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.pingplusplus.android.PaymentActivity}: java.lang.ClassCastException: android.webkit.WebView cannot be cast to com.pingplusplus.android.WebViewEx at  android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
....
Caused by: java.lang.ClassCastException: android.webkit.WebView cannot be cast to com.pingplusplus.android.WebViewEx at com.pingplusplus.android.q.<init>(Unknown Source) at com.pingplusplus.android.PaymentActivity.b(Unknown Source)
...

Such an obvious error should have been detected by any tests if there were any.

**Comment by username4gh** [comment]
update: same issue on version 2.1.5

**Comment by dong11** [comment]
在更新ping++的jar包同时   也需要更新相应的资源文件

**Comment by javalue** [comment]
@dong11 更新哪里的资源？

**Comment by dong11** [comment]
资源文件中的layout @javalue
