### ISSUE TITLE
建议Gradle Version不要用2.1+用确定的版本

### ISSUE THREAD

**Issue by Luolc** [PingPlusPlus/pingpp-android#39]
Gradle脚本中不建议把Version写成形如2.1+的形式，这会导致AS每次的build都会检查更新，极大拖慢速度。而且协同开发时很可能导致不同的人抓取到不同版本的module，很可能导致不可预料的错误。绝大部分开源库都是在README上把最新版本注明上就可以了 #

**Comment by dong11** [comment]
好的 下次会改进  谢谢
