### ISSUE TITLE
添加微信支付编译不了

### ISSUE THREAD

**Issue by Waylenw** [PingPlusPlus/pingpp-android#40]
Error:Execution failed for task ':gettv:transformClassesWithJarMergingForGettvDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/tencent/mm/a/a.class

**Comment by samurai00** [comment]
有没有用微信分享之类的？

**Comment by Waylenw** [comment]
嗯嗯 应该是微信分享的问题

**Comment by samurai00** [comment]
微信相关的，只保留一个 jar 包就可以了。
