### ISSUE TITLE
Ping++和高德地图兼容性

### ISSUE THREAD

**Issue by fashioncj** [PingPlusPlus/pingpp-android#41]
Ping++和高德都是使用gradle导入
---
不设置ndk会导致高德地图找不到so而无法使用
```
        ndk {
            //选择要添加的对应cpu类型的.so库。
            abiFilters 'armeabi'
            // 还可以添加 'x86', 'x86_64', 'mips', 'mips64',, 'armeabi-v7a', 'armeabi-v8a'
        }
```

**Comment by dong11** [comment]
设置了这个 还会导致so文件找不到吗？    因为Ping++ 和  高德 提供的so文件对应的cup类型可能有所不同  需要手动设置

**Comment by fashioncj** [comment]
@dong11  不会。高德不同的sdk提供的so也不尽相同。

**Comment by dong11** [comment]
@fashioncj    我的意思是 比如Ping++ SDK  提供了armeabi、armeabi-v7a 而高德地图提供了armeabi,  当手机是armeabi-v7a的   会去加载armeabi-v7a包下的so文件 这是会报高德地图的so文件找不到   而你上面的代码在打包的时候就只打包了armeabi  所以只会去armeabi包下找 因此不会出现报错     建议使用各种SDK时保持相同的so文件
