### ISSUE TITLE
使用了最新版后在给打包APK时会报一个alipay的类冲突

### ISSUE THREAD

**Issue by zzpuser** [PingPlusPlus/pingpp-android#44]

**Comment by dong11** [comment]
@zzpuser 有Log吗？？

**Comment by zzpuser** [comment]
我引用了
//ping++SDK
compile 'com.pingxx:pingpp-core:2.1.9'
//必须添加
compile 'com.pingxx:pingpp-alipay:2.1.9'
//使用支付宝时添加
compile 'com.pingxx:pingpp-wxpay:2.1.9'
//使用微信支付时添加
LOG如下：

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/alipay/a/a/i;

Error:Execution failed for task ':app:transformClassesWithDexForOtherDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException



解决方法：将所有版本改为2.1.8即可正常打包

在 2017-03-09 13:10:57，"hwongrex" <notifications@github.com> 写道：


@zzpuser 有Log吗？？

**Comment by dong11** [comment]
@zzpuser 你在试试2.1.9的  可能上传到jcenter上有缓存

**Comment by senlinxuefeng** [comment]
@dong11 我的在打包的时候也出现问题了

**Comment by dong11** [comment]
@senlinxuefeng 你把本地的缓存去一下  再试试

**Comment by senlinxuefeng** [comment]
@dong11 我是刚集成了，clean也没不管用

**Comment by dong11** [comment]
@senlinxuefeng 报什么错？

**Comment by senlinxuefeng** [comment]
@dong11 
* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRishiqingRelease'.
> java.io.IOException: Can't write [/Users/yumingchuan/AndroidStudioProjects/AndroidProject/RiShiQing/app/build/intermediates/transforms/proguard/rishiqing/release/jars/3/1f/main.jar] (Can't read [/Users/yumingchuan/AndroidStudioProjects/AndroidProject/RiShiQing/app/build/intermediates/exploded-aar/com.pingxx/pingpp-alipay/2.1.9/jars/libs/alipaySingle-20160825.jar(;;;;;;**.class)] (Duplicate zip entry [alipaySingle-20160825.jar:com/alipay/android/app/IAlixPay$Stub$a.class]))

**Comment by dong11** [comment]
@senlinxuefeng 把gradle下的缓存去一下就行

**Comment by senlinxuefeng** [comment]
@dong11   ./gradlew clean 起清理之后还是不管用，要怎么清理才行呢？

**Comment by dong11** [comment]
@senlinxuefeng 这个是清理项目的
<img width="280" alt="file" src="https://cloud.githubusercontent.com/assets/16264994/23847268/9ac76932-080c-11e7-9110-38b6273a5e39.png">
查看一下存放的路径  将pingpp-alipay删除  或者将整个gradle的缓存文件删除就行

**Comment by senlinxuefeng** [comment]
@dong11 删除后再次打包，还是不行
![image](https://cloud.githubusercontent.com/assets/10865635/23847682/8ed66b1c-080e-11e7-8c54-760ba8592d7b.png)

**Comment by dong11** [comment]
@senlinxuefeng 你确定删干净了？？   我集成是只有一个的， 你可能没删干净，或者你简单的新建一个项目重新集成一下试试

**Comment by senlinxuefeng** [comment]
@dong11 我在一个新的工程中集成的就是这样，出现两个版本
![image](https://cloud.githubusercontent.com/assets/10865635/23847964/da9b159c-080f-11e7-94d7-94ae8528b929.png)

**Comment by dong11** [comment]
@senlinxuefeng  不会啊   我新建了好几个项目，都没有错，你可以在pingpp-alipay右键查看路径，
<img width="479" alt="file" src="https://cloud.githubusercontent.com/assets/16264994/23848130/b19fe680-0810-11e7-9f79-e662827e42d6.png"> 
删除com.pingxx这个目录就行

**Comment by senlinxuefeng** [comment]
@dong11 我这边删掉后一编译就出两个，最后还是通过导入工程引用，好使了

**Comment by yulindyy** [comment]
同样的问题,help
![image](https://user-images.githubusercontent.com/21304932/27320183-9b44600a-55c7-11e7-8dac-51f3f3007d22.png)

Error:Execution failed for task ':autosos:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Can't write [F:\YuLinForWork\autosos\autosos\build\intermediates\transforms\proguard\release\jars\3\1f\main.jar] (Can't read [F:\YuLinForWork\autosos\autosos\build\intermediates\exploded-aar\com.pingxx\pingpp-alipay\2.1.9\jars\libs\alipaySingle-20161222.jar(;;;;;;**.class)] (Duplicate zip entry [alipaySingle-20161222.jar:com/alipay/android/app/IAlixPay$Stub$a.class]))

弄了老半天了,看提示是混淆问题啊

**Comment by dong11** [comment]
@yulindyy （Duplicate zip entry）看一下项目中是不是其他地方也含有alipay相关的库

**Comment by zzpuser** [comment]
没。。没引用支付宝的sdk。这个问题是很早很早之前的了，现在已经解决了😂

发自我的 iPhone

**Comment by SunnyEver0** [comment]
@dong11 你好，项目中本来已经有alipay的库了，但是引用的另一个三方库aar包又包含alipay的，现在报（Duplicate zip entry），这个该怎么解决呢？谢谢！

**Comment by dong11** [comment]
@SunnyEver0 取消 Ping++ 的 alipay 的引用就可以

**Comment by SunnyEver0** [comment]
@dong11 谢谢你，你的意思是改这个ping++的源码，然后再重新打一个ping++的包吗？我们还想继续使用ping++中关于alipay的功能呢，另一个三方库是国外的，又不太好让他们剔除哈。这种情况怎么解决好一点呢

**Comment by dong11** [comment]
@SunnyEver0  不用改源码    移除这个就行 compile 'com.pingxx:pingpp-alipay:2.1.18' // 使用支付宝时添加

**Comment by SunnyEver0** [comment]
@dong11 那移除之后ping++中的alipay功能是不是就不能使用了哎，我们还想继续使用这里面的alipay的功能呢🤣

**Comment by dong11** [comment]
@SunnyEver0 可以的   只要你项目中有 alipay 的就行

**Comment by SunnyEver0** [comment]
@dong11 我这里报找不到alipay的包的错呢
Full recompilation is required because at least one of the classes of removed jar 'alipaySdk-20180403.jar' requires it. Analysis took 0.021 secs.

我现在项目只引入了那个三方的aar哈，那个aar里面有alipay的包。

**Comment by dong11** [comment]
@SunnyEver0  你是怎么依赖 Ping++ SDK 的？

**Comment by SunnyEver0** [comment]
我们是react-native的项目哈，我把它包装成了一个子项目，然后引入进来的。我们第三方的aar包也是包装成了一个子项目，引入的。

**Comment by dong11** [comment]
@SunnyEver0 把 Ping++ 里面封装成子项目 里面 怎么依赖 Ping++ SDK 的？

**Comment by SunnyEver0** [comment]
@dong11 在这个子项目里面引入Ping++ SDK，然后包装了一层func给外部调用的哈

**Comment by dong11** [comment]
@SunnyEver0 你怎么移除 Ping++ 中的 alipay 的？

**Comment by SunnyEver0** [comment]
按你说的那样，把compile 'com.pingxx:pingpp-alipay:2.1.18'这个移除了

**Comment by dong11** [comment]
@SunnyEver0 alipaySdk-20180403.jar 应该被你在哪里引用了吧    Ping++ SDK 里是没有这个的
