### ISSUE TITLE
我使用的是Androidstudio2.2.2，导入demo，运行的时候报这个错误

### ISSUE THREAD

**Issue by youjiankezhan** [PingPlusPlus/pingpp-android#45]
Error:Execution failed for task ':example:transformClassesWithInstantRunForDebug'.
> org/simalliance/openmobileapi/SEService$CallBack

**Comment by dong11** [comment]
这个是集成银联的问题 银联要求Open Mobile API来构建 试试换个编译版本 或者 https://pan.baidu.com/s/1o73HCwU 下载银联提供的jar包来解决

**Comment by chenyusheng** [comment]
我也遇到这个问题，但我把 Androidstudio 的 instant run 关掉之后就正常的，但是我想使用 instant run，下载了你上面的jar ，发现并没有解决问题，可能是我放 jar 位置错了，请问具体要放到 sdk 文件夹下的哪里？（我的 sdk 下没有 add-ons）,是解压之后把addon-open_mobile_api-giesecke_devrient_gmbh-19文件夹整个复制进去还是只复制该文件夹下的内容？

**Comment by dong11** [comment]
@chenyusheng 你确定是上面的问题？？  上面的问题只要下载openmobileapi.jar这个包就行

**Comment by chenyusheng** [comment]
![image](https://cloud.githubusercontent.com/assets/11496107/24447042/3acd650c-14a2-11e7-9e42-2d3bdd21e5bf.png)
开了 instant run 之后的报错：
Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> org/simalliance/openmobileapi/SEService$CallBack

**Comment by dong11** [comment]
@chenyusheng 用这个之后 是不可以用instant run 的     instant run对编译比较严格

**Comment by chenyusheng** [comment]
只要用银联就不能用 instant run吗？之前也有用银联支付，但是还是能用 instant run 的，只是今天升级成最新的 pingpp 依赖之后才出现的

**Comment by dong11** [comment]
@chenyusheng 之前你没用到openmobileapi.jar这个吧

**Comment by chenyusheng** [comment]
现在在代码上也没有改，只是换了依赖，所以现在还是没有用到 openmobileapi.jar 吧

**Comment by dong11** [comment]
@chenyusheng 可以试试这个 
`dependencies {
	compile 'com.pingxx:pingpp-core:2.1.9' //必须添加
    compile 'com.pingxx:pingpp-alipay:2.1.9' //使用支付宝时添加
    compile 'com.pingxx:pingpp-upacp:2.1.9' //使用银联支付时添加
    compile 'com.pingxx:pingpp-wxpay:2.1.9' //使用微信支付时添加
    compile 'com.pingxx:pingpp-bfb-sdk:2.1.9' // 使用百付宝时添加
    compile 'com.pingxx:pingpp-qpay:2.1.9' //使用QQ钱包时添加
}`

**Comment by chenyusheng** [comment]
这个问题在下个版本会解决吗？instant run可以大大加速编译过程，不使用会降低开发效率

**Comment by chenyusheng** [comment]
使用上面方法可以，issue 可以 close 啦~thx~

**Comment by dong11** [comment]
@chenyusheng 如果要用到openmobileapi.jar这个  使用provided依赖就行 不需要使用compile

**Comment by chenyusheng** [comment]
ok~
