### ISSUE TITLE
把 ping 的 jar 更新成最新的依赖项目pingpp之后不能通过编译

### ISSUE THREAD

**Issue by chenyusheng** [PingPlusPlus/pingpp-android#48]
报错如下:
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: a/a/a/a.class

在 debug 了一阵子之后发现把友盟统计的 jar 移除就没有问题了，但是统计功能是要保存的，所以请问现在是要怎么处理才能保留友盟统计与 ping++？

**Comment by dong11** [comment]
@chenyusheng  这个是因为你里面有重复的jar包存在  你看一下哪里重复了  删除就行

**Comment by chenyusheng** [comment]
我已经发现跟友盟统计的 jar 包重复了，但是这个 jar 包又不能删，统计功能是要接着使用的

**Comment by dong11** [comment]
@chenyusheng 加了混淆没有   https://github.com/PingPlusPlus/pingpp-android/blob/master/docs/Ping%2B%2B%E5%AE%89%E5%8D%93SDK%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.md 在文档最后面有

**Comment by chenyusheng** [comment]
混淆是有加的

**Comment by dong11** [comment]
@chenyusheng 应该是你混淆没加对  因为SDK中并不会与友盟统计的冲突

**Comment by chenyusheng** [comment]
发现冲突的主要是 pingpp 中的 alipay

**Comment by dong11** [comment]
@chenyusheng alipay的包名是com.alipay开头的  而你冲突的是啊a.a.a.a  说明你被你给混淆了

**Comment by chenyusheng** [comment]
![image](https://cloud.githubusercontent.com/assets/11496107/24449720/d39eae32-14aa-11e7-8d35-6f5dc23420fc.png)
这应该没毛病啊~

**Comment by dong11** [comment]
@chenyusheng 加在alipay jar包所在的那个module

**Comment by chenyusheng** [comment]
![image](https://cloud.githubusercontent.com/assets/11496107/24450696/64f14072-14ae-11e7-87bd-efe9df8709ac.png)
使用这个方法之后，这个问题就不存在了~
