### ISSUE TITLE
报错信息

### ISSUE THREAD

**Issue by Goach** [PingPlusPlus/pingpp-android#49]
Warning:warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.alipay.android.phone.mrpc.core.DefaultRpcClient$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

请问下这个是什么问题

**Comment by dong11** [comment]
这个是警告,可以忽略   如果真的要去掉可以加个混淆
