### ISSUE TITLE
Ping++招行一网通支付如何配置支付成功后和IOS一样直接返回。而不用配置中间页?即使后台返回的result_url无效。

### ISSUE THREAD

**Issue by AndroidZern** [PingPlusPlus/pingpp-android#50]
Ping++招行一网通支付如何配置支付成功后和IOS一样直接返回。而不用配置中间页?即使后台返回的result_url无效。
IOS端：2.2.8 及以上版本，可选择是否在 WAP 渠道中支付完成后，点击“返回商户”按钮，直接关闭支付页面。开启方法：[Pingpp ignoreResultUrl: YES];注：该方法需在客户端 SDK 中 createPayment 方法前使用。
Android端：并没有相关的文档注释。我自己找了
![image](https://cloud.githubusercontent.com/assets/15031729/24695451/7678eab0-1a18-11e7-84dd-8e65439b99f0.png)
但是无效。请问我如何去配置。使我最后能够直接返回。而不用去跳转到result_url配置de的网址。

**Comment by dong11** [comment]
result_url不要带有端口就行
