### ISSUE TITLE
关于银联支付 sdk 版本问题

### ISSUE THREAD

**Issue by chenyusheng** [PingPlusPlus/pingpp-android#54]
由于使用了 ping++，然后今天收到了银联的邮件说必须使用3.3.2以上的sdk版本，所以请问最新 ping 中的银联 sdk 是什么版本？

**Comment by dong11** [comment]
@chenyusheng 最新的是3.3.5   替换一下银联相关的jar包就行

**Comment by chenyusheng** [comment]
所以最新的 ping++ sdk 包中的银联相关 jar是3.3.5对吧？？？

ps：你上一个回复可以理解成：银联最新的 sdk 是3.3.5，自己替换一下相关 jar 包就好。。。
      也可以理解成：ping 中的银联已经是最新的3.3.5，自己有需要也可以直接替换相关 jar 包。。。

**Comment by dong11** [comment]
@chenyusheng 恩  Ping++SDK中的银联的jar包版本是3.3.5 你如果需要的话可以只替换银联相关的包(包含.so、.jar、 .bin文件)

**Comment by chenyusheng** [comment]
已经是最新的就不用替换啦哈哈哈

**Comment by chenyusheng** [comment]
谢谢哈，我 close 这个 issue 了

**Comment by dong11** [comment]
@chenyusheng 在调起银联支付的过渡页面 会显示银联的版本号  你可以查看一下就行

**Comment by chenyusheng** [comment]
ok，get~
