### ISSUE TITLE
com.alipay.android.phone.mrpc.core.HttpManager$1

### ISSUE THREAD

**Issue by baguosiji** [PingPlusPlus/pingpp-android#55]
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.alipay.android.phone.mrpc.core.HttpManager$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

**Comment by dong11** [comment]
@baguosiji 看一下是不是方法数超了   添加multiDexEnabled true 来解决 试试

**Comment by baguosiji** [comment]
@dong11  可以调了
