### ISSUE TITLE
按照官方文档集成之后不能打包

### ISSUE THREAD

**Issue by yulindyy** [PingPlusPlus/pingpp-android#56]
编译运行没问题,就是打包时候有个错误,搞了老半天了,麻烦帮我看看
先上错误log
Error:Execution failed for task ':autosos:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Can't write [F:\YuLinForWork\autosos\autosos\build\intermediates\transforms\proguard\release\jars\3\1f\main.jar] (Can't read [F:\YuLinForWork\autosos\autosos\build\intermediates\exploded-aar\com.pingxx\pingpp-alipay\2.1.9\jars\libs\alipaySingle-20161222.jar(;;;;;;**.class)] (Duplicate zip entry [alipaySingle-20161222.jar:com/alipay/android/app/IAlixPay$Stub$a.class]))

看错误好像是混淆的问题

混淆也是按照官方文档的
![image](https://user-images.githubusercontent.com/21304932/27320327-4a800a56-55c8-11e7-8db8-65309621dd4f.png)

目前项目中集成了友盟统计最新版,高德地图导航

**Comment by dong11** [comment]
@yulindyy Log上错误是项目中有多个alipay相关的jar包   检查一下是不是哪里多导入了

**Comment by yulindyy** [comment]
现在ok了,原因是lib包里有一个alipay的jar,虽然没引用,但是删掉后打包就OK了..但是运行编译的时候又出了一个dex不能超64k的提示,后来在gradle中添加 multiDexEnabled true,现在运行中正常,谢谢
