### ISSUE TITLE
Failed to resolve: com.pingxx:pingpp-ui:2.1.18，用2.1.16就没事

### ISSUE THREAD

**Issue by ToGallop** [PingPlusPlus/pingpp-android#64]
android sutdio 3.1.2
gralde 3.1.2
Failed to resolve: com.pingxx:pingpp-ui:2.1.18
但是官方不是这样写了吗？
2018年7月4日
dependencies {
   compile 'com.pingxx:pingpp-core:2.1.18' // (Ping++ 标准版 SDK) 必须添加
   compile 'com.pingxx:pingpp-ui:2.1.18' // (Ping++ UI 控件) 使用 Ping++ UI 时添加
   compile 'com.tencent.mm.opensdk:wechat-sdk-android-without-mta:+' // 使用微信支付时添加,具体版本参考微信官方文档
   compile 'com.pingxx:pingpp-alipay:2.1.18' // 使用支付宝时添加
   compile 'com.pingxx:pingpp-upacp:2.1.18' // 使用银联支付时添加
   compile 'com.pingxx:pingpp-qpay:2.1.18' // 使用QQ钱包时添加
   compile 'com.pingxx:pingpp-cmbwallet:2.1.18' // 使用招行一网通时添加
}

**Comment by dong11** [comment]
@ToGallop   重新 rebuild 试试   之前上传 pingpp-ui 失败

**Comment by ToGallop** [comment]
@dong11 嗯，可以了。3Q
