### ISSUE TITLE
可不可以提供gradle 支持？

### ISSUE THREAD

**Issue by lijy91** [PingPlusPlus/pingpp-android#7]
自从用了Android Studio后就不喜欢下载jar包添加到项目了，如果能支持gradle就好了。

**Comment by burulangtu** [comment]
分支[【one】下面有一个基于gradle的版本。

**Comment by burulangtu** [comment]
@lijy91 你是说使用Gradle发布项目到JCenter仓库？

**Comment by lijy91** [comment]
@burulangtu 好像是发布到Maven的仓库。
这样我可以直接在build.gradle添加一行代码就可以引用ping++了
```bash
compile 'com.pingplusplus:pingxx:2.0.3'
```

**Comment by burulangtu** [comment]
@lijy91 好的，我们会尽快推出。

**Comment by palorotolo** [comment]
还没有推出

**Comment by samurai00** [comment]
https://github.com/PingPlusPlus/pingpp-android/blob/master/docs/Ping%2B%2B%E5%AE%89%E5%8D%93SDK%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.md#gradle导入方式

这里有说明
