### ISSUE TITLE
Pingpp.signAgreement调用报错

### ISSUE THREAD

**Issue by lian3139** [PingPlusPlus/pingpp-android#77]
传入agreement对象字符串为：
{
	"id": "agr_19ERglyaeUgLHv",
	"object": "agreement",
	"livemode": false,
	"app": "app_znTq1KeLefb9q9a1",
	"created": 1573040189,
	"channel": "wx",
	"contract_no": "101",
	"contract_id": null,
	"credential": {
		"object": "credential",
		"wx": {
			"credential": "https:\/\/api.mch.weixin.qq.com\/papay\/entrustweb?appid=4b6fe4e6c68131654ee14b146ec2c034&mch_id=1323854561&plan_id=130147&contract_code=101&request_serial=1011573040189558&contract_display_account=155%E5%90%8C%E5%AD%A6&notify_url=https%3A%2F%2Fnotify.pingxx.com%2Fnotify%2Fagreements%2Fagr_19ERglyaeUgLHv&version=1.0&timestamp=1573040189&sign=A61A51C7FE77D1AF60FD44C8EBC41574"
		}
	},
	"status": "created",
	"time_succeeded": null,
	"time_canceled": null,
	"failure_code": null,
	"failure_msg": null,
	"extra": {
		"display_account": "155同学",
		"plan_id": "130147",
		"request_serial": "1011573040189558"
	},
	"metadata": {},
	"source": null
}

错误信息为：
at java.lang.String.substring(String.java:1971)
at com.pingplusplus.android.Pingpp.signAgreement(Unknown Source:29)

**Comment by samurai00** [comment]
fixed
