### ISSUE TITLE
什么时候推出Kotlin版sdk

### ISSUE THREAD

**Issue by sjqnice** [PingPlusPlus/pingpp-android#86]

**Comment by samurai00** [comment]
现在这个 [com.pingxx:pingpp-android:2.3.6](https://mvnrepository.com/artifact/com.pingxx/pingpp-android/2.3.6) 就是 kotlin 写的，编译成 jar 的。Java、Kotlin 都能使用。
你说的是直接是 Kotlin 源码 SDK 吗？

**Comment by sjqnice** [comment]
<img width="315" alt="image" src="https://github.com/PingPlusPlus/pingpp-android/assets/14270796/482a046b-7405-4836-9c8b-5802b0ffddac">
啊，这块显示是Java呀

**Comment by samurai00** [comment]
@sjqnice 这是检测的当前项目中的文件，example 里都是 java 文件。

库里有依赖 kotlin：
<img width="638" alt="截屏2024-04-12 11 13 30" src="https://github.com/PingPlusPlus/pingpp-android/assets/685874/dea4d281-53b3-48ba-a22a-e23434820a3b">

**Comment by sjqnice** [comment]
好的
